# Generated by Django 3.1.2 on 2020-11-18 18:18

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('address_line_1', models.CharField(max_length=254)),
                ('address_line_2', models.CharField(max_length=254)),
                ('town_or_city', models.CharField(max_length=254)),
                ('county_province', models.CharField(max_length=254)),
                ('country', models.CharField(max_length=254)),
                ('post_code_zip_code', models.CharField(max_length=254)),
                ('phone_number', phone_field.models.PhoneField(blank=True, max_length=31)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.address'),
        ),
    ]
