# Generated by Django 3.1.2 on 2020-11-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201121_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='county_province',
            new_name='county_or_province',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='post_code_zip_code',
            new_name='post_code_or_zip_code',
        ),
    ]
