# Generated by Django 3.1.2 on 2020-12-16 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201216_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='primary_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.address'),
        ),
    ]
