# Generated by Django 3.1.2 on 2020-11-19 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20201118_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='primary_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.address'),
        ),
    ]
