# Generated by Django 3.1.2 on 2020-11-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='lineitem_total',
            new_name='line_item_total',
        ),
    ]
