# Generated by Django 3.1.2 on 2020-11-22 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20201121_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='post_code_or_zip',
            new_name='post_code_or_zip_code',
        ),
    ]
