# Generated by Django 3.1.2 on 2020-11-05 20:33

import django.core.validators
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='release_year',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1984), products.models.max_value_current_year]),
        ),
    ]
