# Generated by Django 3.1.2 on 2020-11-10 11:07

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201109_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_year',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1930), products.models.max_value_current_year]),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='products.Tag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tracklist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=254, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
